// <auto-generated />
using Contratacao.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Contratacao.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ContratacaoDbContext))]
[Migration("20260908230000_AddIdempotencyRequestHash")]
partial class AddIdempotencyRequestHash
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Contratacao.Infrastructure.Persistence.IdempotencyRecord", b =>
        {
            b.Property<string>("Chave")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("chave");

            b.Property<Guid>("ContratacaoId")
                .HasColumnType("uuid")
                .HasColumnName("contratacao_id");

            b.Property<string>("HashRequisicao")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("hash_requisicao");

            b.Property<DateTimeOffset>("CriadoEm")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("criado_em");

            b.HasKey("Chave");
            b.ToTable("idempotency_records", (string)null);
        });
#pragma warning restore 612, 618
    }
}
